### ISSUE TITLE
TypeError: schema.s.hooks.createWrapperSync is not a function

### ISSUE THREAD

**Issue by PPCM** [coyotte508/mongo-locks#1]
In a simple example

```
'use strict'

const sleep = require('sleep')
const mongoose = require('mongoose')
const locks = require('mongo-locks')

mongoose.connect('mongodb://localhost:27017/test-semaphore')
  .then(() => {
    locks.init(mongoose.connection) //do just once across the whole app

    console.log('Start')
    return locks.lock("mongo-locks")
  })
  .then((free) => {
    
    console.log('Do something important')
    sleep.sleep(10)
    console.log('Something important done')

    return free()
  })
  .then(() => {
    console.log('Done')
    mongoose.disconnect()
  })
  .catch((error) => {
    console.error(error)
    mongoose.disconnect()
  })
```

I have the error
```
TypeError: schema.s.hooks.createWrapperSync is not a function
    at applyHooks (/home/ppcm/dev/nodejs/semaphore-test/node_modules/mongoose/lib/services/model/applyHooks.js:55:5)
    at Function.compile (/home/ppcm/dev/nodejs/semaphore-test/node_modules/mongoose/lib/model.js:4056:3)
    at Mongoose.model (/home/ppcm/dev/nodejs/semaphore-test/node_modules/mongoose/lib/index.js:389:22)
    at NativeConnection.Connection.model (/home/ppcm/dev/nodejs/semaphore-test/node_modules/mongoose/lib/connection.js:677:23)
    at Object.init (/home/ppcm/dev/nodejs/semaphore-test/node_modules/mongo-locks/index.js:16:24)
    at mongoose.connect.then (/home/ppcm/dev/nodejs/semaphore-test/test-mongo-locks.js:9:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Mongoose version 5.1.2

Any idea why?

**Comment by coyotte508** [comment]
Probably because the module uses version 4.7.6. I'm going to change the mongoose dependency to a peer dependency.

**Comment by coyotte508** [comment]
Added 5.x to the possible versions of mongoose in https://github.com/coyotte508/mongo-locks/commit/74c9cf2afe3491a694e48d818ae3b1f4e5ae4f72. You need to update to the 0.1.0 version of the mongo-locks package.
